title: Justin Jenecke Portfolio
email: justinjenecke@gmail.com
description: >-
  Portfolio website to showcase my coding projects and skills
baseurl: ""
url: "https://justinscottjenecke.github.io/"

github_username: JustinScottJenecke

linkedin_username: Justin Jenecke

author: Justin Scott Jenecke